---
name: Linting

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
  workflow_dispatch:

env:
  DEFAULT_PYTHON: "3.12"

jobs:
  codespell:
    name: codespell
    runs-on: ubuntu-latest
    steps:
      - name: â¤µï¸ Check out code from GitHub
        uses: actions/checkout@v4.1.1
      - name: ğŸ— Set up Poetry
        run: pip install poetry
      - name: ğŸ— Set up Python ${{ env.DEFAULT_PYTHON }}
        id: python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
          cache: "pip"
      - name: ğŸ— Install workflow dependencies
        run: poetry config virtualenvs.create false
      - name: ğŸ— Install Python dependencies
        run: poetry install --no-interaction --no-ansi
      - name: ğŸš€ Check code for common misspellings
        run: pre-commit run codespell --all-files

  ruff:
    name: Ruff
    runs-on: ubuntu-latest
    steps:
      - name: â¤µï¸ Check out code from GitHub
        uses: actions/checkout@v4.1.1
      - name: ğŸ— Set up Poetry
        run: pip install poetry
      - name: ğŸ— Set up Python ${{ env.DEFAULT_PYTHON }}
        id: python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
          cache: "pip"
      - name: ğŸ— Install workflow dependencies
        run: poetry config virtualenvs.create false
      - name: ğŸ— Install Python dependencies
        run: poetry install --no-interaction --no-ansi
      - name: ğŸš€ Run Ruff linter
        run: ruff check --output-format=github .
      - name: ğŸš€ Run Ruff formatter
        run: ruff format --check .

  black:
    name: black
    runs-on: ubuntu-latest
    steps:
      - name: â¤µï¸ Check out code from GitHub
        uses: actions/checkout@v4.1.1
      - name: ğŸ— Set up Poetry
        run: pip install poetry
      - name: ğŸ— Set up Python ${{ env.DEFAULT_PYTHON }}
        id: python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
          cache: "pip"
      - name: ğŸ— Install workflow dependencies
        run: poetry config virtualenvs.create false
      - name: ğŸ— Install Python dependencies
        run: poetry install --no-interaction --no-ansi
      - name: ğŸš€ Run black on docs
        run: blacken-docs

  pre-commit-hooks:
    name: pre-commit-hooks
    runs-on: ubuntu-latest
    steps:
      - name: â¤µï¸ Check out code from GitHub
        uses: actions/checkout@v4.1.1
      - name: ğŸ— Set up Poetry
        run: pip install poetry
      - name: ğŸ— Set up Python ${{ env.DEFAULT_PYTHON }}
        id: python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
          cache: "pip"
      - name: ğŸ— Install workflow dependencies
        run: poetry config virtualenvs.create false
      - name: ğŸ— Install Python dependencies
        run: poetry install --no-interaction --no-ansi
      - name: ğŸš€ Check Python AST
        run: pre-commit run check-ast --all-files
      - name: ğŸš€ Check for case conflicts
        run: pre-commit run check-case-conflict --all-files
      - name: ğŸš€ Check docstring is first
        run: pre-commit run check-docstring-first --all-files
      - name: ğŸš€ Check that executables have shebangs
        run: pre-commit run check-executables-have-shebangs --all-files
      - name: ğŸš€ Check JSON files
        run: pre-commit run check-json --all-files
      - name: ğŸš€ Check for merge conflicts
        run: pre-commit run check-merge-conflict --all-files
      - name: ğŸš€ Check for broken symlinks
        run: pre-commit run check-symlinks --all-files
      - name: ğŸš€ Check TOML files
        run: pre-commit run check-toml --all-files
      - name: ğŸš€ Check XML files
        run: pre-commit run check-xml --all-files
      - name: ğŸš€ Check YAML files
        run: pre-commit run check-yaml --all-files
      - name: ğŸš€ Check YAML files
        run: pre-commit run check-yaml --all-files
      - name: ğŸš€ Detect Private Keys
        run: pre-commit run detect-private-key --all-files
      - name: ğŸš€ Check End of Files
        run: pre-commit run end-of-file-fixer --all-files
      - name: ğŸš€ Trim Trailing Whitespace
        run: pre-commit run trailing-whitespace --all-files

  pylint:
    name: pylint
    runs-on: ubuntu-latest
    steps:
      - name: â¤µï¸ Check out code from GitHub
        uses: actions/checkout@v4.1.1
      - name: ğŸ— Set up Poetry
        run: pip install poetry
      - name: ğŸ— Set up Python ${{ env.DEFAULT_PYTHON }}
        id: python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
          cache: "pip"
      - name: ğŸ— Install workflow dependencies
        run: poetry config virtualenvs.create false
      - name: ğŸ— Install Python dependencies
        run: poetry install --no-interaction --no-ansi
      - name: ğŸš€ Run pylint
        run: pre-commit run pylint --all-files

  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - name: â¤µï¸ Check out code from GitHub
        uses: actions/checkout@v4.1.1
      - name: ğŸ— Set up Poetry
        run: pip install poetry
      - name: ğŸ— Set up Python ${{ env.DEFAULT_PYTHON }}
        id: python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
          cache: "pip"
      - name: ğŸ— Install workflow dependencies
        run: poetry config virtualenvs.create false
      - name: ğŸ— Install Python dependencies
        run: poetry install --no-interaction --no-ansi
      - name: ğŸš€ Run yamllint
        run: yamllint .
